/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SlotId = IDL.Nat;
export const BookAppointmentRequest = IDL.Record({
  'reasonForVisit' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'slotId' : SlotId,
  'phone' : IDL.Text,
});
export const AppointmentId = IDL.Nat;
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Appointment = IDL.Record({
  'id' : AppointmentId,
  'status' : AppointmentStatus,
  'reasonForVisit' : IDL.Text,
  'userId' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'slotId' : SlotId,
  'slotStartTime' : Timestamp,
  'phone' : IDL.Text,
});
export const ArticleCategory = IDL.Variant({
  'reproductiveTesting' : IDL.Null,
  'stress' : IDL.Null,
  'sexualHealth' : IDL.Null,
  'general' : IDL.Null,
  'lifestyle' : IDL.Null,
  'nutrition' : IDL.Null,
});
export const Citation = IDL.Record({
  'title' : IDL.Text,
  'source' : IDL.Text,
  'year' : IDL.Nat,
  'authors' : IDL.Text,
});
export const CreateArticleRequest = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'category' : ArticleCategory,
  'citations' : IDL.Vec(Citation),
});
export const ArticleId = IDL.Nat;
export const ArticlePublic = IDL.Record({
  'id' : ArticleId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishedAt' : Timestamp,
  'updatedAt' : Timestamp,
  'category' : ArticleCategory,
  'citations' : IDL.Vec(Citation),
});
export const BlogPostStatus = IDL.Variant({
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const CreateBlogPostRequest = IDL.Record({
  'status' : BlogPostStatus,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'featuredImageUrl' : IDL.Opt(IDL.Text),
  'excerpt' : IDL.Text,
});
export const BlogPostPublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : BlogPostStatus,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'featuredImageUrl' : IDL.Opt(IDL.Text),
  'excerpt' : IDL.Text,
});
export const AssessmentId = IDL.Nat;
export const AnswerValue = IDL.Variant({
  'nat' : IDL.Nat,
  'bool' : IDL.Bool,
  'text' : IDL.Text,
});
export const QuestionId = IDL.Nat;
export const Answer = IDL.Record({
  'value' : AnswerValue,
  'questionId' : QuestionId,
});
export const Recommendation = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const RiskLevel = IDL.Variant({
  'areasToImprove' : IDL.Null,
  'optimized' : IDL.Null,
  'consultSpecialist' : IDL.Null,
});
export const RiskProfile = IDL.Record({
  'completedAt' : Timestamp,
  'recommendations' : IDL.Vec(Recommendation),
  'overallRisk' : RiskLevel,
});
export const Assessment = IDL.Record({
  'id' : AssessmentId,
  'userId' : UserId,
  'answers' : IDL.Vec(Answer),
  'createdAt' : Timestamp,
  'riskProfile' : RiskProfile,
});
export const PlanningTimeline = IDL.Variant({
  'within1Year' : IDL.Null,
  'moreThan1Year' : IDL.Null,
  'notSure' : IDL.Null,
  'within3Months' : IDL.Null,
  'within6Months' : IDL.Null,
});
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'age' : IDL.Opt(IDL.Nat),
  'healthHistoryConsent' : IDL.Bool,
  'planningTimeline' : IDL.Opt(PlanningTimeline),
  'displayName' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
});
export const ConsultationSlot = IDL.Record({
  'id' : SlotId,
  'startTime' : Timestamp,
  'isAvailable' : IDL.Bool,
  'durationMinutes' : IDL.Nat,
});
export const SubmitAssessmentRequest = IDL.Record({
  'answers' : IDL.Vec(Answer),
});
export const UpdateBlogPostRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : BlogPostStatus,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'featuredImageUrl' : IDL.Opt(IDL.Text),
  'excerpt' : IDL.Text,
});
export const UpdateProfileRequest = IDL.Record({
  'age' : IDL.Opt(IDL.Nat),
  'healthHistoryConsent' : IDL.Bool,
  'planningTimeline' : IDL.Opt(PlanningTimeline),
  'displayName' : IDL.Text,
});

export const idlService = IDL.Service({
  'bookAppointment' : IDL.Func([BookAppointmentRequest], [Appointment], []),
  'canRetakeAssessment' : IDL.Func([], [IDL.Bool], ['query']),
  'cancelAppointment' : IDL.Func([AppointmentId], [IDL.Bool], []),
  'createArticle' : IDL.Func([CreateArticleRequest], [ArticlePublic], []),
  'createBlogPost' : IDL.Func([CreateBlogPostRequest], [BlogPostPublic], []),
  'deleteBlogPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getArticle' : IDL.Func([ArticleId], [IDL.Opt(ArticlePublic)], ['query']),
  'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPostPublic)], ['query']),
  'getMyAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getMyLatestAssessment' : IDL.Func([], [IDL.Opt(Assessment)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
  'listAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPostPublic)], ['query']),
  'listArticles' : IDL.Func([], [IDL.Vec(ArticlePublic)], ['query']),
  'listArticlesByCategory' : IDL.Func(
      [ArticleCategory],
      [IDL.Vec(ArticlePublic)],
      ['query'],
    ),
  'listAvailableSlots' : IDL.Func([], [IDL.Vec(ConsultationSlot)], ['query']),
  'listPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPostPublic)], ['query']),
  'submitAssessment' : IDL.Func([SubmitAssessmentRequest], [Assessment], []),
  'updateBlogPost' : IDL.Func(
      [UpdateBlogPostRequest],
      [IDL.Opt(BlogPostPublic)],
      [],
    ),
  'upsertMyProfile' : IDL.Func([UpdateProfileRequest], [UserProfilePublic], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SlotId = IDL.Nat;
  const BookAppointmentRequest = IDL.Record({
    'reasonForVisit' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'slotId' : SlotId,
    'phone' : IDL.Text,
  });
  const AppointmentId = IDL.Nat;
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Appointment = IDL.Record({
    'id' : AppointmentId,
    'status' : AppointmentStatus,
    'reasonForVisit' : IDL.Text,
    'userId' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'slotId' : SlotId,
    'slotStartTime' : Timestamp,
    'phone' : IDL.Text,
  });
  const ArticleCategory = IDL.Variant({
    'reproductiveTesting' : IDL.Null,
    'stress' : IDL.Null,
    'sexualHealth' : IDL.Null,
    'general' : IDL.Null,
    'lifestyle' : IDL.Null,
    'nutrition' : IDL.Null,
  });
  const Citation = IDL.Record({
    'title' : IDL.Text,
    'source' : IDL.Text,
    'year' : IDL.Nat,
    'authors' : IDL.Text,
  });
  const CreateArticleRequest = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'category' : ArticleCategory,
    'citations' : IDL.Vec(Citation),
  });
  const ArticleId = IDL.Nat;
  const ArticlePublic = IDL.Record({
    'id' : ArticleId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishedAt' : Timestamp,
    'updatedAt' : Timestamp,
    'category' : ArticleCategory,
    'citations' : IDL.Vec(Citation),
  });
  const BlogPostStatus = IDL.Variant({
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const CreateBlogPostRequest = IDL.Record({
    'status' : BlogPostStatus,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'featuredImageUrl' : IDL.Opt(IDL.Text),
    'excerpt' : IDL.Text,
  });
  const BlogPostPublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : BlogPostStatus,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'featuredImageUrl' : IDL.Opt(IDL.Text),
    'excerpt' : IDL.Text,
  });
  const AssessmentId = IDL.Nat;
  const AnswerValue = IDL.Variant({
    'nat' : IDL.Nat,
    'bool' : IDL.Bool,
    'text' : IDL.Text,
  });
  const QuestionId = IDL.Nat;
  const Answer = IDL.Record({
    'value' : AnswerValue,
    'questionId' : QuestionId,
  });
  const Recommendation = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const RiskLevel = IDL.Variant({
    'areasToImprove' : IDL.Null,
    'optimized' : IDL.Null,
    'consultSpecialist' : IDL.Null,
  });
  const RiskProfile = IDL.Record({
    'completedAt' : Timestamp,
    'recommendations' : IDL.Vec(Recommendation),
    'overallRisk' : RiskLevel,
  });
  const Assessment = IDL.Record({
    'id' : AssessmentId,
    'userId' : UserId,
    'answers' : IDL.Vec(Answer),
    'createdAt' : Timestamp,
    'riskProfile' : RiskProfile,
  });
  const PlanningTimeline = IDL.Variant({
    'within1Year' : IDL.Null,
    'moreThan1Year' : IDL.Null,
    'notSure' : IDL.Null,
    'within3Months' : IDL.Null,
    'within6Months' : IDL.Null,
  });
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'age' : IDL.Opt(IDL.Nat),
    'healthHistoryConsent' : IDL.Bool,
    'planningTimeline' : IDL.Opt(PlanningTimeline),
    'displayName' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
  });
  const ConsultationSlot = IDL.Record({
    'id' : SlotId,
    'startTime' : Timestamp,
    'isAvailable' : IDL.Bool,
    'durationMinutes' : IDL.Nat,
  });
  const SubmitAssessmentRequest = IDL.Record({ 'answers' : IDL.Vec(Answer) });
  const UpdateBlogPostRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : BlogPostStatus,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'featuredImageUrl' : IDL.Opt(IDL.Text),
    'excerpt' : IDL.Text,
  });
  const UpdateProfileRequest = IDL.Record({
    'age' : IDL.Opt(IDL.Nat),
    'healthHistoryConsent' : IDL.Bool,
    'planningTimeline' : IDL.Opt(PlanningTimeline),
    'displayName' : IDL.Text,
  });
  
  return IDL.Service({
    'bookAppointment' : IDL.Func([BookAppointmentRequest], [Appointment], []),
    'canRetakeAssessment' : IDL.Func([], [IDL.Bool], ['query']),
    'cancelAppointment' : IDL.Func([AppointmentId], [IDL.Bool], []),
    'createArticle' : IDL.Func([CreateArticleRequest], [ArticlePublic], []),
    'createBlogPost' : IDL.Func([CreateBlogPostRequest], [BlogPostPublic], []),
    'deleteBlogPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getArticle' : IDL.Func([ArticleId], [IDL.Opt(ArticlePublic)], ['query']),
    'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPostPublic)], ['query']),
    'getMyAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getMyLatestAssessment' : IDL.Func([], [IDL.Opt(Assessment)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
    'listAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPostPublic)], ['query']),
    'listArticles' : IDL.Func([], [IDL.Vec(ArticlePublic)], ['query']),
    'listArticlesByCategory' : IDL.Func(
        [ArticleCategory],
        [IDL.Vec(ArticlePublic)],
        ['query'],
      ),
    'listAvailableSlots' : IDL.Func([], [IDL.Vec(ConsultationSlot)], ['query']),
    'listPublishedBlogPosts' : IDL.Func(
        [],
        [IDL.Vec(BlogPostPublic)],
        ['query'],
      ),
    'submitAssessment' : IDL.Func([SubmitAssessmentRequest], [Assessment], []),
    'updateBlogPost' : IDL.Func(
        [UpdateBlogPostRequest],
        [IDL.Opt(BlogPostPublic)],
        [],
      ),
    'upsertMyProfile' : IDL.Func(
        [UpdateProfileRequest],
        [UserProfilePublic],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };