/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Answer { 'value' : AnswerValue, 'questionId' : QuestionId }
export type AnswerValue = { 'nat' : bigint } |
  { 'bool' : boolean } |
  { 'text' : string };
export interface Appointment {
  'id' : AppointmentId,
  'status' : AppointmentStatus,
  'reasonForVisit' : string,
  'userId' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'slotId' : SlotId,
  'slotStartTime' : Timestamp,
  'phone' : string,
}
export type AppointmentId = bigint;
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export type ArticleCategory = { 'reproductiveTesting' : null } |
  { 'stress' : null } |
  { 'sexualHealth' : null } |
  { 'general' : null } |
  { 'lifestyle' : null } |
  { 'nutrition' : null };
export type ArticleId = bigint;
export interface ArticlePublic {
  'id' : ArticleId,
  'title' : string,
  'content' : string,
  'publishedAt' : Timestamp,
  'updatedAt' : Timestamp,
  'category' : ArticleCategory,
  'citations' : Array<Citation>,
}
export interface Assessment {
  'id' : AssessmentId,
  'userId' : UserId,
  'answers' : Array<Answer>,
  'createdAt' : Timestamp,
  'riskProfile' : RiskProfile,
}
export type AssessmentId = bigint;
export interface BlogPostPublic {
  'id' : bigint,
  'status' : BlogPostStatus,
  'title' : string,
  'content' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'featuredImageUrl' : [] | [string],
  'excerpt' : string,
}
export type BlogPostStatus = { 'published' : null } |
  { 'draft' : null };
export interface BookAppointmentRequest {
  'reasonForVisit' : string,
  'name' : string,
  'email' : string,
  'slotId' : SlotId,
  'phone' : string,
}
export interface Citation {
  'title' : string,
  'source' : string,
  'year' : bigint,
  'authors' : string,
}
export interface ConsultationSlot {
  'id' : SlotId,
  'startTime' : Timestamp,
  'isAvailable' : boolean,
  'durationMinutes' : bigint,
}
export interface CreateArticleRequest {
  'title' : string,
  'content' : string,
  'category' : ArticleCategory,
  'citations' : Array<Citation>,
}
export interface CreateBlogPostRequest {
  'status' : BlogPostStatus,
  'title' : string,
  'content' : string,
  'featuredImageUrl' : [] | [string],
  'excerpt' : string,
}
export type PlanningTimeline = { 'within1Year' : null } |
  { 'moreThan1Year' : null } |
  { 'notSure' : null } |
  { 'within3Months' : null } |
  { 'within6Months' : null };
export type QuestionId = bigint;
export interface Recommendation {
  'title' : string,
  'description' : string,
  'category' : string,
}
export type RiskLevel = { 'areasToImprove' : null } |
  { 'optimized' : null } |
  { 'consultSpecialist' : null };
export interface RiskProfile {
  'completedAt' : Timestamp,
  'recommendations' : Array<Recommendation>,
  'overallRisk' : RiskLevel,
}
export type SlotId = bigint;
export interface SubmitAssessmentRequest { 'answers' : Array<Answer> }
export type Timestamp = bigint;
export interface UpdateBlogPostRequest {
  'id' : bigint,
  'status' : BlogPostStatus,
  'title' : string,
  'content' : string,
  'featuredImageUrl' : [] | [string],
  'excerpt' : string,
}
export interface UpdateProfileRequest {
  'age' : [] | [bigint],
  'healthHistoryConsent' : boolean,
  'planningTimeline' : [] | [PlanningTimeline],
  'displayName' : string,
}
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'age' : [] | [bigint],
  'healthHistoryConsent' : boolean,
  'planningTimeline' : [] | [PlanningTimeline],
  'displayName' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
}
export interface _SERVICE {
  'bookAppointment' : ActorMethod<[BookAppointmentRequest], Appointment>,
  'canRetakeAssessment' : ActorMethod<[], boolean>,
  'cancelAppointment' : ActorMethod<[AppointmentId], boolean>,
  'createArticle' : ActorMethod<[CreateArticleRequest], ArticlePublic>,
  'createBlogPost' : ActorMethod<[CreateBlogPostRequest], BlogPostPublic>,
  'deleteBlogPost' : ActorMethod<[bigint], boolean>,
  'getArticle' : ActorMethod<[ArticleId], [] | [ArticlePublic]>,
  'getBlogPost' : ActorMethod<[bigint], [] | [BlogPostPublic]>,
  'getMyAppointments' : ActorMethod<[], Array<Appointment>>,
  'getMyLatestAssessment' : ActorMethod<[], [] | [Assessment]>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'listAllBlogPosts' : ActorMethod<[], Array<BlogPostPublic>>,
  'listArticles' : ActorMethod<[], Array<ArticlePublic>>,
  'listArticlesByCategory' : ActorMethod<
    [ArticleCategory],
    Array<ArticlePublic>
  >,
  'listAvailableSlots' : ActorMethod<[], Array<ConsultationSlot>>,
  'listPublishedBlogPosts' : ActorMethod<[], Array<BlogPostPublic>>,
  'submitAssessment' : ActorMethod<[SubmitAssessmentRequest], Assessment>,
  'updateBlogPost' : ActorMethod<
    [UpdateBlogPostRequest],
    [] | [BlogPostPublic]
  >,
  'upsertMyProfile' : ActorMethod<[UpdateProfileRequest], UserProfilePublic>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];