/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type SlotId = bigint;
export type AppointmentId = bigint;
export type ArticleId = bigint;
export interface SubmitAssessmentRequest {
    answers: Array<Answer>;
}
export type AssessmentId = bigint;
export interface UpdateProfileRequest {
    age?: bigint;
    healthHistoryConsent: boolean;
    planningTimeline?: PlanningTimeline;
    displayName: string;
}
export interface BookAppointmentRequest {
    reasonForVisit: string;
    name: string;
    email: string;
    slotId: SlotId;
    phone: string;
}
export interface UpdateBlogPostRequest {
    id: bigint;
    status: BlogPostStatus;
    title: string;
    content: string;
    featuredImageUrl?: string;
    excerpt: string;
}
export interface Citation {
    title: string;
    source: string;
    year: bigint;
    authors: string;
}
export interface Recommendation {
    title: string;
    description: string;
    category: string;
}
export interface ConsultationSlot {
    id: SlotId;
    startTime: Timestamp;
    isAvailable: boolean;
    durationMinutes: bigint;
}
export interface Assessment {
    id: AssessmentId;
    userId: UserId;
    answers: Array<Answer>;
    createdAt: Timestamp;
    riskProfile: RiskProfile;
}
export type QuestionId = bigint;
export interface UserProfilePublic {
    id: UserId;
    age?: bigint;
    healthHistoryConsent: boolean;
    planningTimeline?: PlanningTimeline;
    displayName: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
}
export type AnswerValue = {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "text";
    text: string;
};
export type UserId = Principal;
export interface RiskProfile {
    completedAt: Timestamp;
    recommendations: Array<Recommendation>;
    overallRisk: RiskLevel;
}
export interface CreateBlogPostRequest {
    status: BlogPostStatus;
    title: string;
    content: string;
    featuredImageUrl?: string;
    excerpt: string;
}
export interface CreateArticleRequest {
    title: string;
    content: string;
    category: ArticleCategory;
    citations: Array<Citation>;
}
export interface Answer {
    value: AnswerValue;
    questionId: QuestionId;
}
export interface Appointment {
    id: AppointmentId;
    status: AppointmentStatus;
    reasonForVisit: string;
    userId: UserId;
    name: string;
    createdAt: Timestamp;
    email: string;
    slotId: SlotId;
    slotStartTime: Timestamp;
    phone: string;
}
export interface ArticlePublic {
    id: ArticleId;
    title: string;
    content: string;
    publishedAt: Timestamp;
    updatedAt: Timestamp;
    category: ArticleCategory;
    citations: Array<Citation>;
}
export interface BlogPostPublic {
    id: bigint;
    status: BlogPostStatus;
    title: string;
    content: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    featuredImageUrl?: string;
    excerpt: string;
}
export enum AppointmentStatus {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export enum ArticleCategory {
    reproductiveTesting = "reproductiveTesting",
    stress = "stress",
    sexualHealth = "sexualHealth",
    general = "general",
    lifestyle = "lifestyle",
    nutrition = "nutrition"
}
export enum BlogPostStatus {
    published = "published",
    draft = "draft"
}
export enum PlanningTimeline {
    within1Year = "within1Year",
    moreThan1Year = "moreThan1Year",
    notSure = "notSure",
    within3Months = "within3Months",
    within6Months = "within6Months"
}
export enum RiskLevel {
    areasToImprove = "areasToImprove",
    optimized = "optimized",
    consultSpecialist = "consultSpecialist"
}
export interface backendInterface {
    bookAppointment(req: BookAppointmentRequest): Promise<Appointment>;
    canRetakeAssessment(): Promise<boolean>;
    cancelAppointment(appointmentId: AppointmentId): Promise<boolean>;
    createArticle(req: CreateArticleRequest): Promise<ArticlePublic>;
    createBlogPost(req: CreateBlogPostRequest): Promise<BlogPostPublic>;
    deleteBlogPost(postId: bigint): Promise<boolean>;
    getArticle(articleId: ArticleId): Promise<ArticlePublic | null>;
    getBlogPost(postId: bigint): Promise<BlogPostPublic | null>;
    getMyAppointments(): Promise<Array<Appointment>>;
    getMyLatestAssessment(): Promise<Assessment | null>;
    getMyProfile(): Promise<UserProfilePublic | null>;
    listAllBlogPosts(): Promise<Array<BlogPostPublic>>;
    listArticles(): Promise<Array<ArticlePublic>>;
    listArticlesByCategory(category: ArticleCategory): Promise<Array<ArticlePublic>>;
    listAvailableSlots(): Promise<Array<ConsultationSlot>>;
    listPublishedBlogPosts(): Promise<Array<BlogPostPublic>>;
    submitAssessment(req: SubmitAssessmentRequest): Promise<Assessment>;
    updateBlogPost(req: UpdateBlogPostRequest): Promise<BlogPostPublic | null>;
    upsertMyProfile(req: UpdateProfileRequest): Promise<UserProfilePublic>;
}
import type { Answer as _Answer, AnswerValue as _AnswerValue, Appointment as _Appointment, AppointmentId as _AppointmentId, AppointmentStatus as _AppointmentStatus, ArticleCategory as _ArticleCategory, ArticleId as _ArticleId, ArticlePublic as _ArticlePublic, Assessment as _Assessment, AssessmentId as _AssessmentId, BlogPostPublic as _BlogPostPublic, BlogPostStatus as _BlogPostStatus, Citation as _Citation, CreateArticleRequest as _CreateArticleRequest, CreateBlogPostRequest as _CreateBlogPostRequest, PlanningTimeline as _PlanningTimeline, QuestionId as _QuestionId, Recommendation as _Recommendation, RiskLevel as _RiskLevel, RiskProfile as _RiskProfile, SlotId as _SlotId, SubmitAssessmentRequest as _SubmitAssessmentRequest, Timestamp as _Timestamp, UpdateBlogPostRequest as _UpdateBlogPostRequest, UpdateProfileRequest as _UpdateProfileRequest, UserId as _UserId, UserProfilePublic as _UserProfilePublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async bookAppointment(arg0: BookAppointmentRequest): Promise<Appointment> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(arg0);
                return from_candid_Appointment_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(arg0);
            return from_candid_Appointment_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async canRetakeAssessment(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.canRetakeAssessment();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.canRetakeAssessment();
            return result;
        }
    }
    async cancelAppointment(arg0: AppointmentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelAppointment(arg0);
            return result;
        }
    }
    async createArticle(arg0: CreateArticleRequest): Promise<ArticlePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createArticle(to_candid_CreateArticleRequest_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ArticlePublic_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createArticle(to_candid_CreateArticleRequest_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ArticlePublic_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBlogPost(arg0: CreateBlogPostRequest): Promise<BlogPostPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createBlogPost(to_candid_CreateBlogPostRequest_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_BlogPostPublic_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBlogPost(to_candid_CreateBlogPostRequest_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_BlogPostPublic_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteBlogPost(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async getArticle(arg0: ArticleId): Promise<ArticlePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticle(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticle(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPost(arg0: bigint): Promise<BlogPostPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPost(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPost(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAppointments();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAppointments();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyLatestAssessment(): Promise<Assessment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLatestAssessment();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLatestAssessment();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllBlogPosts(): Promise<Array<BlogPostPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllBlogPosts();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllBlogPosts();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async listArticles(): Promise<Array<ArticlePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listArticles();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listArticles();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async listArticlesByCategory(arg0: ArticleCategory): Promise<Array<ArticlePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listArticlesByCategory(to_candid_ArticleCategory_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listArticlesByCategory(to_candid_ArticleCategory_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAvailableSlots(): Promise<Array<ConsultationSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAvailableSlots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAvailableSlots();
            return result;
        }
    }
    async listPublishedBlogPosts(): Promise<Array<BlogPostPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPublishedBlogPosts();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPublishedBlogPosts();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitAssessment(arg0: SubmitAssessmentRequest): Promise<Assessment> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAssessment(to_candid_SubmitAssessmentRequest_n46(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Assessment_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAssessment(to_candid_SubmitAssessmentRequest_n46(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Assessment_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBlogPost(arg0: UpdateBlogPostRequest): Promise<BlogPostPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(to_candid_UpdateBlogPostRequest_n53(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(to_candid_UpdateBlogPostRequest_n53(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async upsertMyProfile(arg0: UpdateProfileRequest): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertMyProfile(to_candid_UpdateProfileRequest_n55(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserProfilePublic_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertMyProfile(to_candid_UpdateProfileRequest_n55(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserProfilePublic_n38(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AnswerValue_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnswerValue): AnswerValue {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Answer_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Answer): Answer {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_AppointmentStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_ArticleCategory_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ArticleCategory): ArticleCategory {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ArticlePublic_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ArticlePublic): ArticlePublic {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Assessment_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Assessment): Assessment {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_BlogPostPublic_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPostPublic): BlogPostPublic {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_BlogPostStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPostStatus): BlogPostStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_PlanningTimeline_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlanningTimeline): PlanningTimeline {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_RiskProfile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskProfile): RiskProfile {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ArticlePublic]): ArticlePublic | null {
    return value.length === 0 ? null : from_candid_ArticlePublic_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPostPublic]): BlogPostPublic | null {
    return value.length === 0 ? null : from_candid_BlogPostPublic_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Assessment]): Assessment | null {
    return value.length === 0 ? null : from_candid_Assessment_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlanningTimeline]): PlanningTimeline | null {
    return value.length === 0 ? null : from_candid_PlanningTimeline_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ArticleId;
    title: string;
    content: string;
    publishedAt: _Timestamp;
    updatedAt: _Timestamp;
    category: _ArticleCategory;
    citations: Array<_Citation>;
}): {
    id: ArticleId;
    title: string;
    content: string;
    publishedAt: Timestamp;
    updatedAt: Timestamp;
    category: ArticleCategory;
    citations: Array<Citation>;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        publishedAt: value.publishedAt,
        updatedAt: value.updatedAt,
        category: from_candid_ArticleCategory_n11(_uploadFile, _downloadFile, value.category),
        citations: value.citations
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BlogPostStatus;
    title: string;
    content: string;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    featuredImageUrl: [] | [string];
    excerpt: string;
}): {
    id: bigint;
    status: BlogPostStatus;
    title: string;
    content: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    featuredImageUrl?: string;
    excerpt: string;
} {
    return {
        id: value.id,
        status: from_candid_BlogPostStatus_n19(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        featuredImageUrl: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.featuredImageUrl)),
        excerpt: value.excerpt
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AppointmentId;
    status: _AppointmentStatus;
    reasonForVisit: string;
    userId: _UserId;
    name: string;
    createdAt: _Timestamp;
    email: string;
    slotId: _SlotId;
    slotStartTime: _Timestamp;
    phone: string;
}): {
    id: AppointmentId;
    status: AppointmentStatus;
    reasonForVisit: string;
    userId: UserId;
    name: string;
    createdAt: Timestamp;
    email: string;
    slotId: SlotId;
    slotStartTime: Timestamp;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_AppointmentStatus_n3(_uploadFile, _downloadFile, value.status),
        reasonForVisit: value.reasonForVisit,
        userId: value.userId,
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        slotId: value.slotId,
        slotStartTime: value.slotStartTime,
        phone: value.phone
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AssessmentId;
    userId: _UserId;
    answers: Array<_Answer>;
    createdAt: _Timestamp;
    riskProfile: _RiskProfile;
}): {
    id: AssessmentId;
    userId: UserId;
    answers: Array<Answer>;
    createdAt: Timestamp;
    riskProfile: RiskProfile;
} {
    return {
        id: value.id,
        userId: value.userId,
        answers: from_candid_vec_n28(_uploadFile, _downloadFile, value.answers),
        createdAt: value.createdAt,
        riskProfile: from_candid_RiskProfile_n33(_uploadFile, _downloadFile, value.riskProfile)
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _AnswerValue;
    questionId: _QuestionId;
}): {
    value: AnswerValue;
    questionId: QuestionId;
} {
    return {
        value: from_candid_AnswerValue_n31(_uploadFile, _downloadFile, value.value),
        questionId: value.questionId
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedAt: _Timestamp;
    recommendations: Array<_Recommendation>;
    overallRisk: _RiskLevel;
}): {
    completedAt: Timestamp;
    recommendations: Array<Recommendation>;
    overallRisk: RiskLevel;
} {
    return {
        completedAt: value.completedAt,
        recommendations: value.recommendations,
        overallRisk: from_candid_RiskLevel_n35(_uploadFile, _downloadFile, value.overallRisk)
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    age: [] | [bigint];
    healthHistoryConsent: boolean;
    planningTimeline: [] | [_PlanningTimeline];
    displayName: string;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
}): {
    id: UserId;
    age?: bigint;
    healthHistoryConsent: boolean;
    planningTimeline?: PlanningTimeline;
    displayName: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
} {
    return {
        id: value.id,
        age: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.age)),
        healthHistoryConsent: value.healthHistoryConsent,
        planningTimeline: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.planningTimeline)),
        displayName: value.displayName,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reproductiveTesting: null;
} | {
    stress: null;
} | {
    sexualHealth: null;
} | {
    general: null;
} | {
    lifestyle: null;
} | {
    nutrition: null;
}): ArticleCategory {
    return "reproductiveTesting" in value ? ArticleCategory.reproductiveTesting : "stress" in value ? ArticleCategory.stress : "sexualHealth" in value ? ArticleCategory.sexualHealth : "general" in value ? ArticleCategory.general : "lifestyle" in value ? ArticleCategory.lifestyle : "nutrition" in value ? ArticleCategory.nutrition : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    published: null;
} | {
    draft: null;
}): BlogPostStatus {
    return "published" in value ? BlogPostStatus.published : "draft" in value ? BlogPostStatus.draft : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nat: bigint;
} | {
    bool: boolean;
} | {
    text: string;
}): {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "text";
    text: string;
} {
    return "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    areasToImprove: null;
} | {
    optimized: null;
} | {
    consultSpecialist: null;
}): RiskLevel {
    return "areasToImprove" in value ? RiskLevel.areasToImprove : "optimized" in value ? RiskLevel.optimized : "consultSpecialist" in value ? RiskLevel.consultSpecialist : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): AppointmentStatus {
    return "cancelled" in value ? AppointmentStatus.cancelled : "pending" in value ? AppointmentStatus.pending : "confirmed" in value ? AppointmentStatus.confirmed : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    within1Year: null;
} | {
    moreThan1Year: null;
} | {
    notSure: null;
} | {
    within3Months: null;
} | {
    within6Months: null;
}): PlanningTimeline {
    return "within1Year" in value ? PlanningTimeline.within1Year : "moreThan1Year" in value ? PlanningTimeline.moreThan1Year : "notSure" in value ? PlanningTimeline.notSure : "within3Months" in value ? PlanningTimeline.within3Months : "within6Months" in value ? PlanningTimeline.within6Months : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n1(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Answer>): Array<Answer> {
    return value.map((x)=>from_candid_Answer_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogPostPublic>): Array<BlogPostPublic> {
    return value.map((x)=>from_candid_BlogPostPublic_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ArticlePublic>): Array<ArticlePublic> {
    return value.map((x)=>from_candid_ArticlePublic_n9(_uploadFile, _downloadFile, x));
}
function to_candid_AnswerValue_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnswerValue): _AnswerValue {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function to_candid_Answer_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Answer): _Answer {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_ArticleCategory_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArticleCategory): _ArticleCategory {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_BlogPostStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogPostStatus): _BlogPostStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_CreateArticleRequest_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateArticleRequest): _CreateArticleRequest {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_CreateBlogPostRequest_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateBlogPostRequest): _CreateBlogPostRequest {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_PlanningTimeline_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanningTimeline): _PlanningTimeline {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function to_candid_SubmitAssessmentRequest_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmitAssessmentRequest): _SubmitAssessmentRequest {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateBlogPostRequest_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateBlogPostRequest): _UpdateBlogPostRequest {
    return to_candid_record_n54(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProfileRequest_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProfileRequest): _UpdateProfileRequest {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: BlogPostStatus;
    title: string;
    content: string;
    featuredImageUrl?: string;
    excerpt: string;
}): {
    status: _BlogPostStatus;
    title: string;
    content: string;
    featuredImageUrl: [] | [string];
    excerpt: string;
} {
    return {
        status: to_candid_BlogPostStatus_n15(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        featuredImageUrl: value.featuredImageUrl ? candid_some(value.featuredImageUrl) : candid_none(),
        excerpt: value.excerpt
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    answers: Array<Answer>;
}): {
    answers: Array<_Answer>;
} {
    return {
        answers: to_candid_vec_n48(_uploadFile, _downloadFile, value.answers)
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: AnswerValue;
    questionId: QuestionId;
}): {
    value: _AnswerValue;
    questionId: _QuestionId;
} {
    return {
        value: to_candid_AnswerValue_n51(_uploadFile, _downloadFile, value.value),
        questionId: value.questionId
    };
}
function to_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: BlogPostStatus;
    title: string;
    content: string;
    featuredImageUrl?: string;
    excerpt: string;
}): {
    id: bigint;
    status: _BlogPostStatus;
    title: string;
    content: string;
    featuredImageUrl: [] | [string];
    excerpt: string;
} {
    return {
        id: value.id,
        status: to_candid_BlogPostStatus_n15(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        featuredImageUrl: value.featuredImageUrl ? candid_some(value.featuredImageUrl) : candid_none(),
        excerpt: value.excerpt
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age?: bigint;
    healthHistoryConsent: boolean;
    planningTimeline?: PlanningTimeline;
    displayName: string;
}): {
    age: [] | [bigint];
    healthHistoryConsent: boolean;
    planningTimeline: [] | [_PlanningTimeline];
    displayName: string;
} {
    return {
        age: value.age ? candid_some(value.age) : candid_none(),
        healthHistoryConsent: value.healthHistoryConsent,
        planningTimeline: value.planningTimeline ? candid_some(to_candid_PlanningTimeline_n57(_uploadFile, _downloadFile, value.planningTimeline)) : candid_none(),
        displayName: value.displayName
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    category: ArticleCategory;
    citations: Array<Citation>;
}): {
    title: string;
    content: string;
    category: _ArticleCategory;
    citations: Array<_Citation>;
} {
    return {
        title: value.title,
        content: value.content,
        category: to_candid_ArticleCategory_n7(_uploadFile, _downloadFile, value.category),
        citations: value.citations
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogPostStatus): {
    published: null;
} | {
    draft: null;
} {
    return value == BlogPostStatus.published ? {
        published: null
    } : value == BlogPostStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "text";
    text: string;
}): {
    nat: bigint;
} | {
    bool: boolean;
} | {
    text: string;
} {
    return value.__kind__ === "nat" ? {
        nat: value.nat
    } : value.__kind__ === "bool" ? {
        bool: value.bool
    } : value.__kind__ === "text" ? {
        text: value.text
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanningTimeline): {
    within1Year: null;
} | {
    moreThan1Year: null;
} | {
    notSure: null;
} | {
    within3Months: null;
} | {
    within6Months: null;
} {
    return value == PlanningTimeline.within1Year ? {
        within1Year: null
    } : value == PlanningTimeline.moreThan1Year ? {
        moreThan1Year: null
    } : value == PlanningTimeline.notSure ? {
        notSure: null
    } : value == PlanningTimeline.within3Months ? {
        within3Months: null
    } : value == PlanningTimeline.within6Months ? {
        within6Months: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArticleCategory): {
    reproductiveTesting: null;
} | {
    stress: null;
} | {
    sexualHealth: null;
} | {
    general: null;
} | {
    lifestyle: null;
} | {
    nutrition: null;
} {
    return value == ArticleCategory.reproductiveTesting ? {
        reproductiveTesting: null
    } : value == ArticleCategory.stress ? {
        stress: null
    } : value == ArticleCategory.sexualHealth ? {
        sexualHealth: null
    } : value == ArticleCategory.general ? {
        general: null
    } : value == ArticleCategory.lifestyle ? {
        lifestyle: null
    } : value == ArticleCategory.nutrition ? {
        nutrition: null
    } : value;
}
function to_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Answer>): Array<_Answer> {
    return value.map((x)=>to_candid_Answer_n49(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
